# CPU (Zen 4)
COMMON_FLAGS="-O2 -pipe -march=native -falign-functions=64 -falign-loops=64 -mprefer-vector-width=256 -fomit-frame-pointer -fstack-protector-strong"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# GPU (NVIDIA)
VIDEO_CARDS="nvidia"

# LOCALE
LC_MESSAGES=C.UTF-8

# COMPILATION
MAKEOPTS="-j13 -l12"
EMERGE_DEFAULT_OPTS="--jobs=2 --load-average=10 --complete-graph=y"

# PORTAGE
FEATURES="parallel-fetch candy parallel-install network-sandbox clean-logs ccache"
CCACHE_SIZE="20G"
CCACHE_DIR="/var/cache/ccache"
PORTAGE_NICENESS=10
PORTAGE_IONICE_COMMAND="ionice -c 3 -p \${PID}"
PORTAGE_SCHEDULING_POLICY="idle"

# RUST / GO
RUSTFLAGS="-C opt-level=3 -C target-cpu=native"
GOFLAGS="-ldflags=-s -w"

# LINKER (Mold)
LDFLAGS="-fuse-ld=mold -Wl,-O1 -Wl,--as-needed -Wl,--sort-common"

# LICENSE
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

# USE
USE="minimal xattr caps zstd pipewire pulseaudio dbus screencast wayland X vulkan lto pgo \
     threads opencl nvenc dist-kernel \
     -test -gnome -kde -systemd -debug -feedback -telemetry -stats \
     -reporting -crash-report -crashreporter -crash-handler -analytics -geolocation \
     -update-check -ping -ldap -kerberos -bluetooth -cups -profiling \
     -nls -accessibility -ios -ipod -ipad -emacs -xemacs -examples -coreaudio \ 
     -gnome-keyring -wallet"
