# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[mrtnvgr]
location = /var/db/repos/mrtnvgr
sync-type = git
sync-uri = https://github.com/mrtnvgr/gentoo-overlay.git

[hyproverlay]
location = /var/db/repos/hyproverlay
sync-type = git
sync-uri = https://codeberg.org/hyproverlay/hyproverlay.git
